### ISSUE TITLE
How to install on ubuntu?

### ISSUE THREAD

**Issue by judlup** [hannon235/socket.io-poco#12]
Good day, friend i'm trying to install but when i type cmake .. on folder library,  this show me:

CMake Error: The source directory "/home/gerencia/Escritorio/poco socket/socket.io-poco-master" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

Thank you!

**Comment by hannon235** [comment]
the build process has changed, please open another issue if you still have problems
