### ISSUE TITLE
Configuring Android.mk

### ISSUE THREAD

**Issue by caioketo** [hannon235/socket.io-poco#20]
Sorry if its stupid question, but I couldnt make it work with android ndk.
Already tried everything on Android.mk if someone got a sample one for me to see what I'm making wrong would be so good.

Thanks.

My Android.mk:

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE    := Engine
LOCAL_CFLAGS    := -Werror
LOCAL_SRC_FILES := Engine.cpp Application.cpp RendererES2.cpp Client.cpp IOParser.cpp
LOCAL_LDLIBS    := -llog -lGLESv2 -lEGL -DEGL_EGLEXT_PROTOTYPES
LOCAL_WHOLE_STATIC_LIBRARIES += android_native_app_glue pocofoundation_static poconet_static pocojson_static socketiopoco_static

include $(LOCAL_PATH)/socketiopoco/socket.io-poco/Android.mk
include $(BUILD_SHARED_LIBRARY)

$(call import-module,android/native_app_glue)

Error:
Android NDK: C:/Users/Caio/AndroidStudioProjects/JangadaRes/app/src/main//jni/so
cketiopoco/socket.io-poco/Android.mk:socketiopoco_static: LOCAL_MODULE_FILENAME
should not include file extensions
Android NDK: C:/Users/Caio/AndroidStudioProjects/JangadaRes/app/src/main//jni/so
cketiopoco/socket.io-poco/Android.mk:socketiopoco_static: LOCAL_MODULE_FILENAME
must not contain a file extension
C:/Users/Caio/AndroidStudioProjects/JangadaRes/app/src/main/jni/ndk-build/build/
core/build-shared-library.mk:30: *** Android NDK: Aborting    .  Stop.

**Comment by hannon235** [comment]
build method has been updated to cmake, currently investigating whether https://github.com/taka-no-me/android-cmake.git is an option
