### ISSUE TITLE
too short buffer can stop the reception of messages

### ISSUE THREAD

**Issue by francoisTemasys** [hannon235/socket.io-poco#9]
Problem:
The server was sending a message (socket.emit) and the client using socket.io-poco was not receiving. Any information was triggered in the logger. After this problem the socket was not receiving anything from the server.

What should happen:
Reception of the message in any case. Also after the server emit the message an information can be triggered to check that the client has received something.

Solution
The problem is located in "SIOClientImpl.cpp: SIOClientImpl::receive()" :
```
bool SIOClientImpl::receive() {

	char buffer[1024];
        n = _ws->receiveFrame(buffer, sizeof(buffer), flags);
 ```
Can become:
```
bool SIOClientImpl::receive() {
        _logger->information("I received something...");
	char buffer[1024];
        n = _ws->receiveFrame(buffer, sizeof(buffer), flags); //DONT WORK IF BUFFER TOO SMALL
 ```

**Comment by hannon235** [comment]
this is merged, thanks!
